version: '3.8'

services:
  hotel:
    image: proyecto
    build:
      context: .
      dockerfile: Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD:
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
